# Generated by Django 4.1.1 on 2022-09-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
                ('pincodes', models.JSONField(blank=True, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.CharField(blank=True, max_length=256, null=True)),
                ('lon', models.CharField(blank=True, max_length=256, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('worker_pincode', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_assigned', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.admin')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker')),
            ],
        ),
    ]
