# Generated by Django 4.1.1 on 2022-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
