# Generated by Django 4.1.1 on 2022-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customerticket_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
