# Generated by Django 4.1.1 on 2022-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_customerticket_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlocationdetails',
            name='date_of_service',
            field=models.DateField(blank=True, null=True),
        ),
    ]
