# Generated by Django 4.1.1 on 2022-09-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_workerlocationdetails_date_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('date', models.DateField()),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker')),
            ],
        ),
    ]
