# Generated by Django 4.1.1 on 2022-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_workerlivelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='servicing',
            field=models.BooleanField(default=False),
        ),
    ]
