# Generated by Django 4.1.1 on 2022-09-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_customerticket_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.worker')),
            ],
        ),
    ]
