# Generated by Django 4.1.1 on 2022-09-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_workerotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
