# Generated by Django 4.1.1 on 2022-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_customerticket_start_time_customerticket_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerticket',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
